package com.servebeer.please.solarmax.array;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class ArrayManager {

    // hard code it for now
    private static final Set<SolarmaxDevice> solarmaxDevices = new HashSet<SolarmaxDevice>(
            Arrays.asList(new SolarmaxDevice("192.168.1.151", 12345, 1),
                    new SolarmaxDevice("192.168.1.152", 12345, 2)));

    /**
     * @return the Watts of power currently being generated by the array of SolarMax Devices
     */
    public static int getCurrentlyGeneratedPower() {
        int totalPower = 0;
        for (SolarmaxDevice solarmaxDevice : solarmaxDevices) {
            totalPower = totalPower + solarmaxDevice.getCurrentlyGeneratedPower();
        }
        return totalPower;
    }

    public static String ping() {
        String returnString = "";
        for (SolarmaxDevice solarmaxDevice : solarmaxDevices) {
            returnString = returnString + solarmaxDevice.toString();
        }
        return returnString;
    }

    public Set<SolarmaxDevice> getSolarmaxDevices() {
        return solarmaxDevices;
    }
}
